### ISSUE TITLE
app.use() require a middleware function 

### ISSUE THREAD

**Issue by shashwat0802** [bradtraversy/node_passport_login#74]
I am running into the this error shown in the image I literally copy pasted the whole code and still I am running into this error
<img width="1179" alt="Screenshot 2020-06-20 at 9 20 04 PM" src="https://user-images.githubusercontent.com/63670167/85205899-f39fcd00-b33b-11ea-8445-6059fed0ba2c.png">

**Comment by Shawn1912** [comment]
>Try adding this line before the app.use() line `const app = express();`.

**Comment by shashwat0802** [comment]
@Shawn1912  thanks for your response but I found out what the error was and thought of mentioning it here
I mistakenly installed 'express-sessions' which is the wrong package it is 'express-session' instead without the s
